Repository redis/RedisInsight, pull requests merged in 2022-08, with the labels that each got.

#972 #RI-3178,3347- update pub/sub styles, fix scanning text appearence
  redisinsight/ui/src/components/keys-summary/KeysSummary.tsx
  redisinsight/ui/src/pages/pubSub/components/subscription-panel/SubscriptionPanel.tsx
  redisinsight/ui/src/pages/pubSub/components/subscription-panel/styles.module.scss
  redisinsight/ui/src/pages/pubSub/styles.module.scss
Labels: bug

#976 #RI-3354 - add categories to notifications
  redisinsight/api/migration/1659614625861-notification-category.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/modules/notification/dto/create-notification.dto.ts
  redisinsight/api/src/modules/notification/entities/notification.entity.ts
  redisinsight/api/src/modules/notification/notification.service.spec.ts
  redisinsight/api/test/api/notifications/GET-notifications.test.ts
  redisinsight/api/test/api/notifications/notifications.json
  redisinsight/api/test/helpers/constants.ts
  redisinsight/ui/src/components/navigation-menu/components/notifications-center/Notification/Notification.tsx
  redisinsight/ui/src/components/navigation-menu/components/notifications-center/Notification/index.ts
  redisinsight/ui/src/components/navigation-menu/components/notifications-center/NotificationCenter.tsx
  redisinsight/ui/src/components/navigation-menu/components/notifications-center/PopoverNotification/PopoverNotification.tsx
  redisinsight/ui/src/components/navigation-menu/components/notifications-center/styles.module.scss
  redisinsight/ui/src/slices/interfaces/app.ts
Labels: status: in progress

#987 WIP:#RI-3075-replace dbsize command with info keyspace
  redisinsight/api/src/modules/browser/constants/browser-tool-commands.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/cluster.strategy.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/cluster.strategy.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.ts
  redisinsight/api/src/modules/bulk-actions/providers/bulk-actions.provider.spec.ts
Labels: bug

#996 #RI-3223-add hex formatter
  redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/KeyValueFormatter.tsx
  redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/constants.ts
  redisinsight/ui/src/utils/formatters/bufferFormatters.ts
  redisinsight/ui/src/utils/formatters/valueFormatters.tsx
  redisinsight/ui/src/utils/tests/formatters/bufferFormatters.spec.ts
Labels: feature

#1000 #RI-3178-update low log and [ub/sub pages styles
  redisinsight/ui/src/pages/pubSub/components/subscription-panel/styles.module.scss
  redisinsight/ui/src/pages/slowLog/styles.module.scss
Labels: bug

#1012 #RI-2977-add workbench raw mode
  redisinsight/api/migration/1660664717573-workbench-mode.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/common/transformers/index.ts
  redisinsight/api/src/common/transformers/redis-reply/formatter-manager.spec.ts
  redisinsight/api/src/common/transformers/redis-reply/formatter-manager.ts
  redisinsight/api/src/common/transformers/redis-reply/formatter.interface.ts
  redisinsight/api/src/common/transformers/redis-reply/index.ts
  redisinsight/api/src/common/transformers/redis-reply/strategies/ascii-formatter.strategey.spec.ts
  redisinsight/api/src/common/transformers/redis-reply/strategies/ascii-formatter.strategy.ts
  redisinsight/api/src/common/transformers/redis-reply/strategies/utf8-formatter.strategy.spec.ts
  redisinsight/api/src/common/transformers/redis-reply/strategies/utf8-formatter.strategy.ts
  redisinsight/api/src/modules/cli/services/cli-business/output-formatter/strategies/utf-8-formatter.strategy.ts
  redisinsight/api/src/modules/workbench/dto/create-command-execution.dto.ts
  redisinsight/api/src/modules/workbench/dto/create-command-executions.dto.ts
  redisinsight/api/src/modules/workbench/entities/command-execution.entity.ts
  redisinsight/api/src/modules/workbench/models/command-execution.ts
  redisinsight/api/src/modules/workbench/plugins.service.spec.ts
  redisinsight/api/src/modules/workbench/providers/command-execution.provider.spec.ts
  redisinsight/api/src/modules/workbench/providers/command-execution.provider.ts
  redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.spec.ts
  redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.ts
  redisinsight/api/src/modules/workbench/workbench.service.spec.ts
  redisinsight/api/src/utils/cli-helper.ts
  redisinsight/api/test/api/plugins/POST-instance-id-plugins-command_executions.test.ts
  redisinsight/api/test/api/workbench/GET-instance-id-workbench-command_executions-id.test.ts
  redisinsight/api/test/api/workbench/GET-instance-id-workbench-command_executions.test.ts
  redisinsight/api/test/helpers/local-db.ts
  redisinsight/ui/src/components/query-card/QueryCard.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/styles.module.scss
  redisinsight/ui/src/components/query/Query/Query.tsx
  redisinsight/ui/src/components/query/Query/styles.module.scss
  redisinsight/ui/src/components/query/QueryWrapper.tsx
  redisinsight/ui/src/constants/storage.ts
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResultsWrapper.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx
  redisinsight/ui/src/slices/interfaces/workbench.ts
  redisinsight/ui/src/slices/workbench/wb-results.ts
  redisinsight/ui/src/telemetry/events.ts
Labels: feature

#1031 #RI-3419- change styles
  redisinsight/ui/src/assets/img/icons/raw_mode.svg
  redisinsight/ui/src/components/query/Query/Query.tsx
  redisinsight/ui/src/components/query/Query/styles.module.scss
  redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss
  redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss
  redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss
  redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
Labels: bug

#1033 #RI-2977-add rawMode
  redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.ts
Labels: feature

#1046 #RI-2977-add more space
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/styles.module.scss
Labels: bug

#1037 #RI-3319-add tooltip to field cell
  redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
Labels: feature

#1059 #RI-3331-add java formatter
  package.json
  redisinsight/ui/src/constants/keys.ts
  redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/constants.ts
  redisinsight/ui/src/utils/formatters/bufferFormatters.ts
  redisinsight/ui/src/utils/formatters/utils.ts
  redisinsight/ui/src/utils/formatters/valueFormatters.tsx
  redisinsight/ui/src/utils/tests/formatters/bufferFormatters.spec.ts
  yarn.lock
Labels: feature
