Repository redis/RedisInsight, pull requests merged in 2023-02, with the labels that each got.

#1635 Feature/ri 4034 export connections
  package.json
  redisinsight/api/src/modules/database/database.controller.ts
  redisinsight/api/src/modules/database/database.service.spec.ts
  redisinsight/api/src/modules/database/database.service.ts
  redisinsight/api/src/modules/database/dto/export.databases.dto.ts
  redisinsight/api/src/modules/database/models/export-database.ts
  redisinsight/api/test/api/database/POST-databases-export.test.ts
  redisinsight/ui/src/components/index.ts
  redisinsight/ui/src/components/scan-more/ScanMore.spec.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/mocks/handlers/instances/instancesHandlers.ts
  redisinsight/ui/src/mocks/res/responseComposition.ts
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/DatabasesList.spec.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/DatabasesList.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/action-bar/ActionBar.spec.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/action-bar/ActionBar.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/action-bar/styles.module.scss
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/delete-action/DeleteAction.spec.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/delete-action/DeleteAction.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/export-action/ExportAction.spec.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/export-action/ExportAction.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/index.ts
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesList/components/styles.module.scss
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.spec.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/styles.module.scss
  redisinsight/ui/src/slices/instances/instances.ts
  redisinsight/ui/src/slices/tests/instances/instances.spec.ts
  redisinsight/ui/src/telemetry/events.ts
  tests/e2e/common-actions/databases-actions.ts
  tests/e2e/helpers/api/api-database.ts
  tests/e2e/helpers/conf.ts
  tests/e2e/helpers/database.ts
  tests/e2e/pageObjects/add-redis-database-page.ts
  tests/e2e/pageObjects/my-redis-databases-page.ts
  tests/e2e/rte.docker-compose.yml
  tests/e2e/rte/oss-standalone-tls/Dockerfile
  tests/e2e/rte/oss-standalone-tls/certs/redis.crt
  tests/e2e/rte/oss-standalone-tls/certs/redis.key
  tests/e2e/rte/oss-standalone-tls/certs/redisCA.crt
  tests/e2e/rte/oss-standalone-tls/certs/user.crt
  tests/e2e/rte/oss-standalone-tls/certs/user.key
  tests/e2e/tests/critical-path/database/clone-databases.e2e.ts
  tests/e2e/tests/critical-path/database/connecting-to-the-db.e2e.ts
  tests/e2e/tests/critical-path/database/export-databases.e2e.ts
  tests/e2e/tests/critical-path/database/modules.e2e.ts
  tests/e2e/tests/critical-path/monitor/save-commands.e2e.ts
  tests/e2e/tests/regression/browser/keys-all-databases.e2e.ts
  tests/e2e/tests/regression/cli/cli-re-cluster.e2e.ts
  tests/e2e/tests/regression/database/database-list-search.e2e.ts
  tests/e2e/tests/regression/database/database-sorting.e2e.ts
  tests/e2e/tests/regression/workbench/workbench-re-cluster.e2e.ts
  tests/e2e/tests/smoke/database/add-sentinel-db.e2e.ts
  tests/e2e/tests/smoke/database/connecting-to-the-db.e2e.ts
  yarn.lock
Labels: 2.20

#1696 #RI-3934 - add test connection button
  redisinsight/ui/src/components/notifications/success-messages.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/pages/home/HomePage.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.spec.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/styles.module.scss
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.spec.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
  redisinsight/ui/src/slices/instances/instances.ts
  redisinsight/ui/src/slices/tests/instances/instances.spec.ts
  redisinsight/ui/src/telemetry/events.ts
Labels: feature

#1702 #RI-4156 - update merge process
  redisinsight/api/src/modules/database/database.service.ts
Labels: bug

#1625 #RI-3857 - Save key name filter used
  redisinsight/api/config/default.ts
  redisinsight/api/config/ormconfig.ts
  redisinsight/api/migration/1673934231410-workbench-and-analysis-db.ts
  redisinsight/api/migration/1674539211397-browser-history.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/__mocks__/browser-history.ts
  redisinsight/api/src/__mocks__/index.ts
  redisinsight/api/src/common/constants/history.ts
  redisinsight/api/src/common/constants/index.ts
  redisinsight/api/src/constants/error-messages.ts
  redisinsight/api/src/constants/redis-keys.ts
  redisinsight/api/src/modules/browser/browser.module.ts
  redisinsight/api/src/modules/browser/controllers/history/browser-history.controller.ts
  redisinsight/api/src/modules/browser/dto/browser-history/create.browser-history.dto.ts
  redisinsight/api/src/modules/browser/dto/browser-history/delete.browser-history.dto.ts
  redisinsight/api/src/modules/browser/dto/browser-history/delete.browser-history.response.dto.ts
  redisinsight/api/src/modules/browser/dto/browser-history/get.browser-history.dto.ts
  redisinsight/api/src/modules/browser/entities/browser-history.entity.ts
  redisinsight/api/src/modules/browser/providers/history/browser-history.provider.ts
  redisinsight/api/src/modules/browser/services/browser-history/browser-history.service.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
  redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.spec.ts
  redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.ts
  redisinsight/ui/src/components/multi-search/MultiSearch.spec.tsx
  redisinsight/ui/src/components/multi-search/MultiSearch.tsx
  redisinsight/ui/src/components/multi-search/styles.module.scss
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/constants/keys.ts
  redisinsight/ui/src/pages/browser/BrowserPage.tsx
  redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
  redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx
  redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
  redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.tsx
  redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.spec.tsx
  redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/top-keys/Table.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/top-namespace/Table.tsx
  redisinsight/ui/src/slices/browser/keys.ts
  redisinsight/ui/src/slices/browser/redisearch.ts
  redisinsight/ui/src/slices/interfaces/keys.ts
  redisinsight/ui/src/slices/interfaces/redisearch.ts
  redisinsight/ui/src/slices/tests/browser/keys.spec.ts
  redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts
  tests/e2e/pageObjects/browser-page.ts
  tests/e2e/tests/critical-path/browser/filtering-history.e2e.ts
  tests/e2e/tests/critical-path/browser/search-capabilities.e2e.ts
  tests/e2e/tests/regression/browser/resize-columns.e2e.ts
Labels: 2.20

#1653 #RI-4069 - add client list visualization
  redisinsight/ui/src/packages/clients-list/README.md
  redisinsight/ui/src/packages/clients-list/package.json
  redisinsight/ui/src/packages/clients-list/src/App.tsx
  redisinsight/ui/src/packages/clients-list/src/assets/table_view_icon_dark.svg
  redisinsight/ui/src/packages/clients-list/src/assets/table_view_icon_light.svg
  redisinsight/ui/src/packages/clients-list/src/components/TableResult/TableResult.spec.tsx
  redisinsight/ui/src/packages/clients-list/src/components/TableResult/TableResult.tsx
  redisinsight/ui/src/packages/clients-list/src/components/TableResult/index.ts
  redisinsight/ui/src/packages/clients-list/src/components/index.ts
  redisinsight/ui/src/packages/clients-list/src/icons/arrow_down.js
  redisinsight/ui/src/packages/clients-list/src/icons/arrow_left.js
  redisinsight/ui/src/packages/clients-list/src/icons/arrow_right.js
  redisinsight/ui/src/packages/clients-list/src/icons/check.js
  redisinsight/ui/src/packages/clients-list/src/icons/copy.js
  redisinsight/ui/src/packages/clients-list/src/icons/cross.js
  redisinsight/ui/src/packages/clients-list/src/icons/empty.js
  redisinsight/ui/src/packages/clients-list/src/index.html
  redisinsight/ui/src/packages/clients-list/src/main.tsx
  redisinsight/ui/src/packages/clients-list/src/result.json
  redisinsight/ui/src/packages/clients-list/src/styles/styles.scss
  redisinsight/ui/src/packages/clients-list/src/utils/cachedIcons.ts
  redisinsight/ui/src/packages/clients-list/src/utils/index.ts
  redisinsight/ui/src/packages/clients-list/src/utils/parseResponse.ts
  redisinsight/ui/src/packages/clients-list/tsconfig.json
  redisinsight/ui/src/packages/clients-list/yarn.lock
  scripts/build-statics.cmd
  scripts/build-statics.sh
  tests/e2e/common-actions/workbench-actions.ts
  tests/e2e/pageObjects/workbench-page.ts
  tests/e2e/tests/regression/monitor/monitor.e2e.ts
  tests/e2e/tests/regression/workbench/command-results.e2e.ts
Labels: 2.20

#1704 #RI-4157 - reset context on edit
  redisinsight/api/src/modules/database/database.analytics.spec.ts
  redisinsight/api/src/modules/database/database.analytics.ts
  redisinsight/api/src/modules/database/database.service.spec.ts
  redisinsight/ui/src/pages/home/HomePage.tsx
  redisinsight/ui/src/pages/home/components/AddDatabases/AddDatabasesContainer.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.spec.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DatabaseForm.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DbInfo.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.spec.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
  redisinsight/ui/src/pages/redisStack/components/edit-connection/EditConnection.tsx
Labels: bug

#1648 Fe/feature/ri 4021 telemetry
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.spec.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
Labels: 2.20

#1728 #RI-4133 - remove notification in /overview
  redisinsight/ui/src/slices/instances/instances.ts
  redisinsight/ui/src/slices/tests/instances/instances.spec.ts
Labels: feature

#1713 #RI-3995 - add key into list
  redisinsight/ui/src/constants/keys.ts
  redisinsight/ui/src/slices/browser/keys.ts
  redisinsight/ui/src/slices/tests/browser/keys.spec.ts
  redisinsight/ui/src/slices/tests/instances/instances.spec.ts
  tests/e2e/common-actions/browser-actions.ts
  tests/e2e/tests/regression/browser/add-keys.e2e.ts
Labels: feature

#1741 Fe/feature/ri 4061 upload json
  redisinsight/ui/src/components/monaco-json/MonacoJson.tsx
  redisinsight/ui/src/components/uploadFile/UploadFile.spec.tsx
  redisinsight/ui/src/components/uploadFile/UploadFile.tsx
  redisinsight/ui/src/components/uploadFile/index.ts
  redisinsight/ui/src/components/uploadFile/styles.module.scss
  redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.spec.tsx
  redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.tsx
  redisinsight/ui/src/telemetry/events.ts
  tests/e2e/pageObjects/browser-page.ts
  tests/e2e/test-data/upload-json/sample.json
  tests/e2e/tests/regression/browser/upload-json-key.e2e.ts
Labels: feature

#1745 #RI-4178-4189 - update text content
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DatabaseForm.tsx
  redisinsight/ui/src/pages/home/components/CloudConnection/CloudConnectionForm/CloudConnectionForm.tsx
Labels: feature

#1744 #RI-4177 - remove port from telemetry event
  redisinsight/api/src/modules/database/database.analytics.spec.ts
  redisinsight/api/src/modules/database/database.analytics.ts
Labels: bug

#1772 #RI-4217-4219 - update styles
  redisinsight/ui/src/components/upload-file/UploadFile.spec.tsx
  redisinsight/ui/src/components/upload-file/UploadFile.tsx
  redisinsight/ui/src/components/upload-file/index.ts
  redisinsight/ui/src/components/upload-file/styles.module.scss
  redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.tsx
  redisinsight/ui/src/pages/home/HomePage.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
  redisinsight/ui/src/pages/home/components/CloudConnection/CloudConnectionForm/CloudConnectionForm.tsx
  redisinsight/ui/src/pages/home/components/ClusterConnection/ClusterConnectionForm/ClusterConnectionForm.tsx
  redisinsight/ui/src/pages/home/styles.scss
  redisinsight/ui/src/pages/pubSub/components/publish-message/PublishMessage.tsx
  redisinsight/ui/src/pages/redisCloudDatabases/RedisCloudDatabases/RedisCloudDatabases.tsx
  redisinsight/ui/src/pages/redisCloudDatabasesResult/RedisCloudDatabasesResult.tsx
  redisinsight/ui/src/pages/redisCloudSubscriptions/RedisCloudSubscriptions/RedisCloudSubscriptions.tsx
  redisinsight/ui/src/pages/redisCluster/RedisClusterDatabases.tsx
  redisinsight/ui/src/pages/redisCluster/RedisClusterDatabasesResult.tsx
  redisinsight/ui/src/pages/sentinelDatabases/components/SentinelDatabases/SentinelDatabases.tsx
  redisinsight/ui/src/pages/sentinelDatabasesResult/components/SentinelDatabasesResult/SentinelDatabasesResult.tsx
Labels: bug

#1790 #RI-4244 - fix workbench icon issue
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
Labels: bug
