Repository redis/RedisInsight, pull requests merged in 2023-05, with the labels that each got.

#2013 #RI-4204 - don't run multiple type commands
  redisinsight/api/src/modules/browser/dto/keys.dto.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/cluster.strategy.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.ts
  redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.spec.ts
  redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.ts
  redisinsight/api/test/api/keys/POST-databases-id-keys-get_infos.test.ts
  redisinsight/api/test/api/keys/POST-databases-id-keys.test.ts
  redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
  redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
  redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
  redisinsight/ui/src/slices/browser/keys.ts
  redisinsight/ui/src/slices/tests/browser/keys.spec.ts
Labels: 2.26

#2021 #RI-4340 - fix multiple tooltips on the list of dbs
  redisinsight/ui/src/components/index.ts
  redisinsight/ui/src/components/show-child-by-condition/ShowChildByCondition.spec.tsx
  redisinsight/ui/src/components/show-child-by-condition/ShowChildByCondition.tsx
  redisinsight/ui/src/components/show-child-by-condition/index.ts
  redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
Labels: 2.26

#2042 #RI-4363 - remove bulb icon from recommendations
  redisinsight/ui/src/assets/img/icons/recommendation.svg
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
Labels: bug

#2048 RI-4351 - add key names in recommendation
  redisinsight/api/migration/1683006064293-database-recommendation-params.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/core.module.ts
  redisinsight/api/src/modules/browser/services/hash-business/hash-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/hash-business/hash-business.service.ts
  redisinsight/api/src/modules/browser/services/set-business/set-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/set-business/set-business.service.ts
  redisinsight/api/src/modules/browser/services/string-business/string-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/string-business/string-business.service.ts
  redisinsight/api/src/modules/browser/services/z-set-business/z-set-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/z-set-business/z-set-business.service.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.controller.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.module.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
  redisinsight/api/src/modules/database-recommendation/dto/database-recommendations.response.ts
  redisinsight/api/src/modules/database-recommendation/entities/database-recommendation.entity.ts
  redisinsight/api/src/modules/database-recommendation/models/database-recommendation-params.ts
  redisinsight/api/src/modules/database-recommendation/models/database-recommendation.ts
  redisinsight/api/src/modules/database-recommendation/models/index.ts
  redisinsight/api/src/modules/database-recommendation/models/integersInSet.ts
  redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/repositories/database-recommendation.repository.ts
  redisinsight/api/src/modules/database-recommendation/repositories/local.database.recommendation.repository.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.strategy.interface.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendations.scanner.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendations.scanner.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/abstract.recommendation.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/abstract.recommendation.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/avoid-logical-databases.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/avoid-logical-databases.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/default.recommendation.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/default.recommendation.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-JSON.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-JSON.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-visualization.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-visualization.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/shard-hash.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/shard-hash.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/string-to-json.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/string-to-json.strategy.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/api/database-recommendations/constants.ts
  redisinsight/api/test/helpers/data/redis.ts
Labels: feature

#2082 #RI-4478 - remove graph and searchString recommendations
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
  redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.spec.ts
  redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
  redisinsight/api/src/modules/database-recommendation/models/index.ts
  redisinsight/api/src/modules/database-recommendation/models/searchString.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/src/utils/recommendation-helper.spec.ts
  redisinsight/api/src/utils/recommendation-helper.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/api/database-recommendations/WS-new-recommendations.test.ts
  redisinsight/api/test/helpers/constants.ts
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
Labels: feature

#2090 Fe/feature/ri 4409 improve recommendations
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
  redisinsight/ui/src/slices/interfaces/recommendations.ts
  redisinsight/ui/src/utils/index.ts
  redisinsight/ui/src/utils/recommendation/index.ts
  redisinsight/ui/src/utils/recommendation/styles.module.scss
  redisinsight/ui/src/utils/recommendation/utils.tsx
  redisinsight/ui/src/utils/tests/recommendation/utils.spec.tsx
Labels: feature

#2088 Be/feature/ri 4409 improve recommendations
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/avoid-lua-scripts.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-amount-connected-clients.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-string.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/compression-for-list.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/shard-hash.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/use-smaller-keys.strategy.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
  redisinsight/ui/src/slices/interfaces/recommendations.ts
  redisinsight/ui/src/utils/index.ts
  redisinsight/ui/src/utils/recommendation/index.ts
  redisinsight/ui/src/utils/recommendation/styles.module.scss
  redisinsight/ui/src/utils/recommendation/utils.tsx
  redisinsight/ui/src/utils/tests/recommendation/utils.spec.tsx
Labels: feature

#2097 #RI-4472 - remove very useful vote
  redisinsight/ui/src/assets/img/icons/double_like.svg
  redisinsight/ui/src/assets/img/icons/github-white.svg
  redisinsight/ui/src/assets/img/icons/petard.svg
  redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.spec.tsx
  redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.tsx
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/VoteOption.spec.tsx
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/VoteOption.tsx
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/index.ts
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/styles.module.scss
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/utils.ts
  redisinsight/ui/src/components/recommendation-voting/styles.module.scss
  redisinsight/ui/src/constants/recommendations.ts
Labels: feature

#2101 #RI-4409 - fix static
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
Labels: bug

#2102 #RI-4533-4528 - fix styles
  redisinsight/ui/src/components/recommendation-voting/components/vote-option/VoteOption.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
  redisinsight/ui/src/utils/recommendation/styles.module.scss
  redisinsight/ui/src/utils/recommendation/utils.tsx
Labels: bug

#2106 #RI-4447 - update bulk actions telemetry
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteFooter/BulkDeleteFooter.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
  redisinsight/ui/src/telemetry/events.ts
  redisinsight/ui/src/utils/index.ts
  redisinsight/ui/src/utils/telemetry.ts
  redisinsight/ui/src/utils/tests/telemetry.spec.ts
Labels: feature

#2105 #RI-4447 - update bulk actions telemetry
  redisinsight/api/src/__mocks__/analytics.ts
  redisinsight/api/src/constants/telemetry-events.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions-analytics.service.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/abstract.bulk-action.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/delete.bulk-action.simple.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/providers/bulk-actions.provider.spec.ts
  redisinsight/api/src/modules/bulk-actions/providers/bulk-actions.provider.ts
  redisinsight/api/src/utils/analytics-helper.ts
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteFooter/BulkDeleteFooter.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
  redisinsight/ui/src/telemetry/events.ts
  redisinsight/ui/src/utils/index.ts
  redisinsight/ui/src/utils/telemetry.ts
  redisinsight/ui/src/utils/tests/telemetry.spec.ts
Labels: feature

#2113 #RI-4538-4539-4540 - fix telemetry in bulk actions
  redisinsight/api/src/modules/bulk-actions/bulk-actions-analytics.service.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions.service.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.ts
  redisinsight/ui/src/constants/bulkActions.ts
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/constants/bulk-type-options.tsx
Labels: bug

#2115 #RI-4538 - update telemetry fields names
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.ts
  redisinsight/api/src/modules/bulk-actions/constants/index.ts
  redisinsight/ui/src/constants/bulkActions.ts
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteFooter/BulkDeleteFooter.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/constants/bulk-type-options.tsx
Labels: bug

#2108 #RI-4447 - update bulk actions telemetry (#2105)
  redisinsight/api/src/__mocks__/analytics.ts
  redisinsight/api/src/constants/telemetry-events.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions-analytics.service.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-actions.service.ts
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.spec.ts
  redisinsight/api/src/modules/bulk-actions/bulk-import.service.ts
  redisinsight/api/src/modules/bulk-actions/constants/index.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/abstract.bulk-action.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/models/runners/simple/delete.bulk-action.simple.runner.spec.ts
  redisinsight/api/src/modules/bulk-actions/providers/bulk-actions.provider.spec.ts
  redisinsight/api/src/modules/bulk-actions/providers/bulk-actions.provider.ts
  redisinsight/api/src/utils/analytics-helper.ts
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteFooter/BulkDeleteFooter.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
  redisinsight/ui/src/telemetry/events.ts
  redisinsight/ui/src/utils/index.ts
  redisinsight/ui/src/utils/telemetry.ts
  redisinsight/ui/src/utils/tests/telemetry.spec.ts
Labels: feature

#2119 Fe/feature/ri 4529 4545 insight styles
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
Labels: feature

#2116 #RI-4487 - fix be path
  redisinsight/api/src/modules/custom-tutorial/providers/custom-tutorial.manifest.provider.spec.ts
  redisinsight/api/src/modules/custom-tutorial/providers/custom-tutorial.manifest.provider.ts
  redisinsight/api/src/utils/index.ts
  redisinsight/api/src/utils/path.spec.ts
  redisinsight/api/src/utils/path.ts
Labels: bug

#2114 #RI-4537 - remove uniq condition
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.ts
Labels: feature

#2126 #RI-4461 - fix workbench tooltip
  redisinsight/ui/src/components/navigation-menu/components/help-menu/HelpMenu.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.spec.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsTabs/BulkActionsTabs.spec.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
  redisinsight/ui/src/styles/base/_monaco.scss
Labels: bug

#2130 Fe/feature/ri 4566 update recommendations static
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/utils/recommendation/styles.module.scss
Labels: 2.26

#2129 #RI-4566 - update recommendation conditions
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/modules/browser/services/set-business/set-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/set-business/set-business.service.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/api/database-recommendations/WS-new-recommendations.test.ts
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/utils/recommendation/styles.module.scss
Labels: 2.26

#2132 #RI-4569 - update rts recommendation
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/timestamp.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/timestamp.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/src/utils/recommendation-helper.spec.ts
  redisinsight/api/src/utils/recommendation-helper.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/helpers/constants.ts
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
Labels: 2.26

#2138 #RI-4574 - fix copy btn truncate
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.spec.tsx
Labels: bug
