Repository redis/RedisInsight, pull requests merged in 2023-07, with the labels that each got.

#2275 #RI-4698 - reset input value
  redisinsight/ui/src/components/upload-file/UploadFile.spec.tsx
  redisinsight/ui/src/components/upload-file/UploadFile.tsx
  redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.spec.tsx
  redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/AddLibrary/AddLibrary.tsx
Labels: bug

#2283 #RI-4596 - add recommendations for triggered and functions
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/constants/redis-modules.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
  redisinsight/api/src/modules/database-analysis/database-analysis.service.ts
  redisinsight/api/src/modules/database-analysis/scanner/keys-scanner.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/functions-with-keyspace.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/functions-with-keyspace.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/functions-with-streams.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/functions-with-streams.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/lua-to-functions.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/lua-to-functions.strategy.ts
  redisinsight/api/src/modules/database/database-connection.service.spec.ts
  redisinsight/api/src/modules/database/database-connection.service.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/src/modules/triggered-functions/models/index.ts
  redisinsight/api/src/modules/triggered-functions/models/library.ts
  redisinsight/api/src/modules/triggered-functions/models/short-function.ts
  redisinsight/api/src/modules/triggered-functions/models/short-library.ts
  redisinsight/api/src/utils/recommendation-helper.spec.ts
  redisinsight/api/src/utils/recommendation-helper.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/helpers/constants.ts
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
Labels: 2.30

#2303 #RI-4596 - update condition for luaToFunctions recommendation
  redisinsight/api/src/common/constants/recommendations.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/lua-to-functions.strategy.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
Labels: 2.30

#2294 #RI-4608 - remove GRAPH commands from command helper
  redisinsight/ui/src/components/command-helper/CommandHelperWrapper.spec.tsx
  redisinsight/ui/src/components/command-helper/CommandHelperWrapper.tsx
  redisinsight/ui/src/constants/keys.ts
  redisinsight/ui/src/constants/workbenchResults.ts
  redisinsight/ui/src/slices/app/redis-commands.ts
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/utils/cliHelper.tsx
  redisinsight/ui/src/utils/tests/cliHelper.spec.ts
  tests/e2e/tests/critical-path/cli/cli-command-helper.e2e.ts
Labels: 2.30

#2307 #RI-4726, 4727 - fix utm in the links
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
Labels: bug

#2313 #RI-4586 - align BE and FE getModules summary
  redisinsight/api/src/constants/redis-modules.ts
  redisinsight/api/src/utils/redis-modules-summary.spec.ts
  redisinsight/api/src/utils/redis-modules-summary.ts
Labels: 2.30

#2327 Fe/bugfix/ri 4737 graph command helper
  redisinsight/ui/src/components/command-helper/CommandHelperWrapper.tsx
  redisinsight/ui/src/utils/cliHelper.tsx
  redisinsight/ui/src/utils/tests/cliHelper.spec.ts
Labels: bug

#2295 #RI-4586 - add redisgears 2 icon and text
  redisinsight/api/src/constants/redis-modules.ts
  redisinsight/api/src/utils/redis-modules-summary.spec.ts
  redisinsight/api/src/utils/redis-modules-summary.ts
  redisinsight/ui/src/assets/img/modules/RedisGears2Dark.svg
  redisinsight/ui/src/assets/img/modules/RedisGears2Light.svg
  redisinsight/ui/src/components/database-list-modules/DatabaseListModules.tsx
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/telemetry/interfaces.ts
  redisinsight/ui/src/telemetry/telemetryUtils.spec.ts
  redisinsight/ui/src/telemetry/telemetryUtils.ts
  redisinsight/ui/src/utils/modules.ts
Labels: 2.30

#2316 #RI-4632 - add cluster refresh in triggers and functions
  redisinsight/api/src/modules/triggered-functions/dto/delete-library.dto.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.controller.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
  redisinsight/api/test/api/triggered-functions/DELETE-databases-id-library.test.ts
  redisinsight/api/test/api/triggered-functions/GET-databases-id-functions.test.ts
  redisinsight/api/test/api/triggered-functions/GET-databases-id-libraries.test.ts
  redisinsight/api/test/api/triggered-functions/POST-databases-id-library.test.ts
  redisinsight/api/test/helpers/constants.ts
  redisinsight/api/test/helpers/data/redis.ts
  redisinsight/api/test/test-runs/gears-clu/docker-compose.yml
Labels: 2.30

#2349 Fe/feature/ri 4579 module not loaded
  redisinsight/api/src/constants/redis-modules.ts
  redisinsight/api/src/utils/redis-modules-summary.spec.ts
  redisinsight/api/src/utils/redis-modules-summary.ts
  redisinsight/ui/src/components/messages/module-not-loaded/ModuleNotLoaded.tsx
  redisinsight/ui/src/components/messages/module-not-loaded/styles.module.scss
  redisinsight/ui/src/components/navigation-menu/NavigationMenu.tsx
  redisinsight/ui/src/components/onboarding-features/OnboardingFeatures.spec.tsx
  redisinsight/ui/src/components/onboarding-features/OnboardingFeatures.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/constants/featuresHighlighting.tsx
  redisinsight/ui/src/constants/workbenchResults.ts
  redisinsight/ui/src/pages/browser/components/auto-refresh/AutoRefresh.tsx
  redisinsight/ui/src/pages/triggeredFunctions/TriggeredFunctionsPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/components/NoLibrariesScreen/NoLibrariesScreen.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/components/NoLibrariesScreen/NoLibrariesScreen.tsx
  redisinsight/ui/src/pages/triggeredFunctions/components/NoLibrariesScreen/index.ts
  redisinsight/ui/src/pages/triggeredFunctions/components/NoLibrariesScreen/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/FunctionsPage.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/FunctionsPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/components/FunctionsList/FunctionsList.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/components/FunctionsList/FunctionsList.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/NoLibrariesScreen/NoLibrariesScreen.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/NoLibrariesScreen/NoLibrariesScreen.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/NoLibrariesScreen/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/styles.modules.scss
  redisinsight/ui/src/pages/workbench/constants.ts
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/slices/interfaces/triggeredFunctions.ts
  redisinsight/ui/src/slices/tests/triggeredFunctions/triggeredFunctions.spec.ts
  redisinsight/ui/src/slices/triggeredFunctions/triggeredFunctions.ts
  redisinsight/ui/src/telemetry/interfaces.ts
  redisinsight/ui/src/telemetry/pageViews.ts
  redisinsight/ui/src/telemetry/telemetryUtils.spec.ts
  redisinsight/ui/src/telemetry/telemetryUtils.ts
  redisinsight/ui/src/utils/cliHelper.tsx
  tests/e2e/pageObjects/triggers-and-functions-functions-page.ts
  tests/e2e/tests/critical-path/triggers-and-functions/libraries.e2e.ts
  tests/e2e/tests/regression/browser/onboarding.e2e.ts
Labels: feature

#2369 #RI-4679 - add hello 3 to unsupport commands and add custom error mes…
  redisinsight/api/src/modules/cli/utils/getUnsupportedCommands.spec.ts
  redisinsight/api/src/modules/cli/utils/getUnsupportedCommands.ts
  redisinsight/api/src/modules/workbench/utils/getUnsupportedCommands.spec.ts
  redisinsight/api/src/modules/workbench/utils/getUnsupportedCommands.ts
  redisinsight/api/test/api/cli/POST-databases-id-cli-uuid-send_command.test.ts
  redisinsight/api/test/api/info/GET-info-cli-unsupported-commands.test.ts
  redisinsight/api/test/api/workbench/POST-databases-id-workbench-command_executions.test.ts
  redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
  redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
  redisinsight/ui/src/constants/cliOutput.tsx
  redisinsight/ui/src/constants/commands.ts
Labels: 2.30

#2372 #RI-4579 - update icons
  redisinsight/ui/src/assets/img/triggers_and_functions_dark.svg
  redisinsight/ui/src/assets/img/triggers_and_functions_light.svg
  redisinsight/ui/src/pages/triggeredFunctions/components/NoLibrariesScreen/styles.module.scss
Labels: 2.30

#2336 #RI-4624 - change learn more link
  redisinsight/desktop/src/lib/menu/menu.ts
  redisinsight/desktop/src/lib/tray/tray.ts
Labels: 2.30

#2368 #RI-4768 - Change design for recommendations
  redisinsight/ui/src/assets/img/icons/snooze.svg
  redisinsight/ui/src/assets/img/icons/stars.svg
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/components/recommendation-copy-component/styles.module.scss
Labels: 2.30

#2383 Fe/bugfix/ri 4776 4778 icon and loading
  electron-builder.json
  redisinsight/ui/src/assets/img/triggers_and_functions_dark.svg
  redisinsight/ui/src/assets/img/triggers_and_functions_light.svg
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/FunctionsPage.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Functions/FunctionsPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.tsx
Labels: 2.30

#2388 #RI-4780 - update links
  redisinsight/ui/src/components/database-overview/components/MoreInfoPopover/MoreInfoPopover.tsx
  redisinsight/ui/src/components/messages/filter-not-available/FilterNotAvailable.tsx
  redisinsight/ui/src/components/onboarding-features/OnboardingFeatures.tsx
  redisinsight/ui/src/constants/links.ts
  redisinsight/ui/src/constants/workbenchResults.ts
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.spec.tsx
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/Messages.tsx
Labels: bug, 2.30

#2386 #RI-4699 - 500 error on connecting to user with -@dangerous rule
  redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts
  redisinsight/api/src/modules/database/providers/database-info.provider.ts
Labels: 2.32

#2387 #RI-4669 - add delete all workbench history endpoint
  redisinsight/api/src/modules/workbench/repositories/command-execution.repository.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.spec.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.ts
  redisinsight/api/src/modules/workbench/workbench.controller.ts
  redisinsight/api/src/modules/workbench/workbench.service.spec.ts
  redisinsight/api/src/modules/workbench/workbench.service.ts
  redisinsight/api/test/api/workbench/DELETE-databases-id-workbench-command_executions.test.ts
Labels: feature, 2.32

#2373 #RI-4669 - fe part for clear workbench history
  redisinsight/api/src/modules/workbench/repositories/command-execution.repository.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.spec.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.ts
  redisinsight/api/src/modules/workbench/workbench.controller.ts
  redisinsight/api/src/modules/workbench/workbench.service.spec.ts
  redisinsight/api/src/modules/workbench/workbench.service.ts
  redisinsight/api/test/api/workbench/DELETE-databases-id-workbench-command_executions.test.ts
  redisinsight/ui/src/components/query-card/QueryCard.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/pages/workbench/WorkbenchPage.spec.tsx
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/styles.module.scss
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResultsWrapper.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.spec.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx
  redisinsight/ui/src/slices/interfaces/workbench.ts
  redisinsight/ui/src/slices/tests/workbench/wb-results.spec.ts
  redisinsight/ui/src/slices/workbench/wb-results.ts
  redisinsight/ui/src/styles/components/_buttons.scss
  redisinsight/ui/src/telemetry/events.ts
Labels: 2.32

#2335 Dependabot fixes
  package.json
  redisinsight/api/package.json
  redisinsight/api/src/common/models/client-metadata.ts
  redisinsight/api/src/modules/browser/dto/browser-history/create.browser-history.dto.ts
  redisinsight/api/src/modules/browser/dto/browser-history/get.browser-history.dto.ts
  redisinsight/api/src/modules/browser/dto/redisearch.ts
  redisinsight/api/src/modules/bulk-actions/dto/create-bulk-action.dto.ts
  redisinsight/api/src/modules/bulk-actions/models/bulk-action-filter.ts
  redisinsight/api/src/modules/cloud/autodiscovery/dto/add-cloud-database.dto.ts
  redisinsight/api/src/modules/cloud/autodiscovery/dto/get-cloud-subscription-database.dto.ts
  redisinsight/api/src/modules/cloud/autodiscovery/dto/get-cloud-subscription-databases.dto.ts
  redisinsight/api/src/modules/cloud/autodiscovery/models/cloud-database-details.ts
  redisinsight/api/src/modules/custom-tutorial/models/custom-tutorial.manifest.ts
  redisinsight/api/src/modules/database-analysis/models/scan-filter.ts
  redisinsight/api/src/modules/database-recommendation/dto/modify.database-recommendation.dto.ts
  redisinsight/api/src/modules/database/dto/update.database.dto.ts
  redisinsight/api/src/modules/database/models/database.ts
  redisinsight/api/src/modules/pub-sub/dto/subscription.dto.ts
  redisinsight/api/yarn.lock
  redisinsight/ui/src/packages/redistimeseries-app/yarn.lock
  redisinsight/yarn.lock
  tests/e2e/package.json
  tests/e2e/yarn.lock
  yarn.lock
Labels: 2.32

#2379 #RI-4671 - fix scroll in wb
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx
Labels: 2.32

#2397 Feature/ri 4669 clear wb history
  redisinsight/api/src/modules/workbench/repositories/command-execution.repository.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.spec.ts
  redisinsight/api/src/modules/workbench/repositories/local-command-execution.repository.ts
  redisinsight/api/src/modules/workbench/workbench.controller.ts
  redisinsight/api/src/modules/workbench/workbench.service.spec.ts
  redisinsight/api/src/modules/workbench/workbench.service.ts
  redisinsight/api/test/api/workbench/DELETE-databases-id-workbench-command_executions.test.ts
  redisinsight/ui/src/components/query-card/QueryCard.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/pages/workbench/WorkbenchPage.spec.tsx
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/styles.module.scss
  redisinsight/ui/src/pages/workbench/components/wb-results/WBResultsWrapper.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.spec.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx
  redisinsight/ui/src/slices/interfaces/workbench.ts
  redisinsight/ui/src/slices/tests/workbench/wb-results.spec.ts
  redisinsight/ui/src/slices/workbench/wb-results.ts
  redisinsight/ui/src/styles/components/_buttons.scss
  redisinsight/ui/src/telemetry/events.ts
  tests/e2e/pageObjects/workbench-page.ts
  tests/e2e/tests/regression/workbench/command-results.e2e.ts
Labels: 2.32
