Repository redis/RedisInsight, pull requests merged in 2023-09, with the labels that each got.

#2556 #RI-4899 - change survey text
  redisinsight/ui/src/components/bottom-group-components/components/bottom-group-minimized/BottomGroupMinimized.tsx
Labels: feature

#2555 #RI-4922 - fix json big string view
  redisinsight/ui/src/pages/browser/components/rejson-details/RejsonDetails/RejsonDetails.tsx
Labels: bug

#2459 add sentinel deletion
  tests/e2e/helpers/api/api-database.ts
  tests/e2e/tests/regression/database/database-list-search.e2e.ts
Labels: 2.34

#2496 #RI-3807 - SlowLog - set milliseconds by default
  redisinsight/api/src/modules/slow-log/slow-log-analytics.service.ts
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.spec.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/constants/durationUnits.tsx
  redisinsight/ui/src/mocks/data/oauth.ts
  redisinsight/ui/src/mocks/handlers/index.ts
  redisinsight/ui/src/mocks/handlers/oauth/cloud.ts
  redisinsight/ui/src/mocks/handlers/oauth/index.ts
  redisinsight/ui/src/pages/browser/components/stream-details/consumers-view/ConsumersViewWrapper.tsx
  redisinsight/ui/src/pages/browser/components/stream-details/messages-view/MessageClaimPopover/MessageClaimPopover.tsx
  redisinsight/ui/src/pages/settings/components/cloud-settings/CloudSettings.spec.tsx
  redisinsight/ui/src/pages/slowLog/SlowLogPage.tsx
  redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.spec.tsx
  redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.tsx
  redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx
  redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/styles.module.scss
  redisinsight/ui/src/pages/slowLog/components/SlowLogTable/SlowLogTable.tsx
  redisinsight/ui/src/slices/app/context.ts
  redisinsight/ui/src/slices/tests/app/context.spec.ts
  redisinsight/ui/src/utils/transformers/formatDate.ts
Labels: 2.34

#2594 #RI-4941 - add utm into triggers and functions and welcome screen
  redisinsight/ui/src/slices/interfaces/cloud.ts
  redisinsight/ui/src/utils/oauth/cloudSsoUtm.tsx
  redisinsight/ui/src/utils/tests/oauth/cloudSsoUtm.spec.tsx
Labels: 2.32

#2569 #RI-4882 - add modules import
  redisinsight/api/src/modules/database-import/database-import.service.spec.ts
  redisinsight/api/src/modules/database-import/database-import.service.ts
  redisinsight/api/src/modules/database-import/dto/import.database.dto.ts
  redisinsight/api/src/modules/database/models/additional.redis.module.ts
  redisinsight/api/src/modules/database/models/database.ts
Labels: bug

#2593 #RI-4944 - rework browser navigation
  redisinsight/ui/src/components/database-overview/DatabaseOverview.tsx
  redisinsight/ui/src/components/database-overview/DatabaseOverviewWrapper.tsx
  redisinsight/ui/src/components/database-overview/components/MoreInfoPopover/MoreInfoPopover.tsx
  redisinsight/ui/src/components/database-overview/styles.module.scss
  redisinsight/ui/src/components/instance-header/InstanceHeader.spec.tsx
  redisinsight/ui/src/components/instance-header/InstanceHeader.tsx
  redisinsight/ui/src/components/instance-header/styles.module.scss
  redisinsight/ui/src/pages/browser/BrowserPage.test.tsx
  redisinsight/ui/src/pages/browser/BrowserPage.tsx
  redisinsight/ui/src/pages/browser/components/add-key/AddKey.tsx
  redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
  redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.tsx
  redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.spec.tsx
  redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx
  redisinsight/ui/src/pages/browser/components/key-details/KeyDetails/KeyDetails.tsx
  redisinsight/ui/src/pages/browser/styles.module.scss
  tests/e2e/pageObjects/browser-page.ts
  tests/e2e/pageObjects/components/overview-panel.ts
  tests/e2e/tests/critical-path/browser/bulk-delete.e2e.ts
  tests/e2e/tests/critical-path/browser/key-details.e2e.ts
  tests/e2e/tests/critical-path/browser/keylist-actions.e2e.ts
  tests/e2e/tests/critical-path/browser/search-capabilities.e2e.ts
  tests/e2e/tests/critical-path/database-overview/database-overview.e2e.ts
  tests/e2e/tests/critical-path/database/connecting-to-the-db.e2e.ts
  tests/e2e/tests/regression/database/redisstack.e2e.ts
  tests/e2e/tests/regression/insights/feature-flag.e2e.ts
  tests/e2e/tests/smoke/database/add-standalone-db.e2e.ts
Labels: 2.34

#2493 #RI-3478 - automatic update dependencies versions
  .circleci/config.yml
  .circleci/deps-licenses-report.js
  .gitignore
  package.json
  scripts/build-statics.sh
  yarn.lock
Labels: 2.34

#2599 RI-4893: Add system theme option
  redisinsight/desktop/app.ts
  redisinsight/desktop/config.json
  redisinsight/desktop/src/lib/app/ipc.handlers.ts
  redisinsight/ui/src/App.tsx
  redisinsight/ui/src/components/theme/ThemeComponent.spec.tsx
  redisinsight/ui/src/components/theme/ThemeComponent.tsx
  redisinsight/ui/src/constants/themes.tsx
  redisinsight/ui/src/contexts/themeContext.tsx
  redisinsight/ui/src/electron/constants/ipcEvent.ts
  redisinsight/ui/src/pages/settings/SettingsPage.tsx
  redisinsight/ui/src/services/theme.ts
Labels: 2.34

#2613 #RI-4965 ignore all modules that starts from RedisStackCompat (case i…
  redisinsight/api/config/features-config.json
Labels: 2.34
