Repository redis/RedisInsight, pull requests merged in 2023-04, with the labels that each got.

#1846 #RI-4181 - add to tutorial button for recommendations
  redisinsight/ui/src/components/config/Config.spec.tsx
  redisinsight/ui/src/components/config/Config.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendation-voting/styles.module.scss
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
  redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/getFileInfo.ts
  redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/tests/getFileInfo.spec.ts
  redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementAreaWrapper.spec.tsx
  redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementAreaWrapper.tsx
  redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.spec.tsx
  redisinsight/ui/src/telemetry/events.ts
  tests/e2e/pageObjects/browser-page.ts
  tests/e2e/pageObjects/memory-efficiency-page.ts
  tests/e2e/pageObjects/workbench-page.ts
  tests/e2e/tests/critical-path/memory-efficiency/recommendations.e2e.ts
Labels: 2.24

#1940 #RI-4255 - update recommendations
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/modules/browser/services/hash-business/hash-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/hash-business/hash-business.service.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
  redisinsight/api/src/modules/database/database-info.service.spec.ts
  redisinsight/api/src/modules/database/database-info.service.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.spec.ts
  redisinsight/api/src/modules/recommendation/providers/recommendation.provider.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
  redisinsight/api/test/helpers/constants.ts
Labels: feature

#1941 #RI-4255 - align recomemndations
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.spec.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
  redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/data-nav-tabs/DatabaseAnalysisTabs.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/data-nav-tabs/DatabaseAnalysisTabs.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
  redisinsight/ui/src/slices/interfaces/recommendations.ts
  redisinsight/ui/src/telemetry/events.ts
Labels: feature

#1969 #RI-4255 - remove compres hash recommendation
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
Labels: 2.24

#1972 Be/feature/ri 4257 sync recommendations
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/modules/database-analysis/database-analysis.service.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
  redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.ts
  redisinsight/api/src/utils/recommendation-helper.spec.ts
  redisinsight/api/src/utils/recommendation-helper.ts
  redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
Labels: 2.24

#1973 #RI-4257 - remove liveTimeText
  redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.spec.ts
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
  redisinsight/ui/src/slices/interfaces/recommendations.ts
Labels: 2.24

#1983 #RI-4415 - fix styles
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/databaseAnalysis/components/data-nav-tabs/styles.module.scss
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
Labels: bug

#1992 #RI-4432 - update styles
  redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
Labels: bug
