Repository redis/RedisInsight, pull requests merged in 2023-06, with the labels that each got.

#2121 Feature/ri 4367 autoscroll profiler
  redisinsight/ui/src/components/monitor/Monitor/Monitor.tsx
  redisinsight/ui/src/components/monitor/Monitor/styles.module.scss
  redisinsight/ui/src/components/monitor/MonitorOutputList/MonitorOutputList.tsx
  redisinsight/ui/src/components/monitor/MonitorWrapper.tsx
  redisinsight/ui/src/pages/pubSub/components/messages-list/MessagesList/MessagesList.tsx
  redisinsight/ui/src/slices/cli/monitor.ts
Labels: 2.28

#2144 #RI-4541 - add subscribe error message
  redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
  redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
  redisinsight/ui/src/constants/cliOutput.tsx
  redisinsight/ui/src/constants/commands.ts
  tests/e2e/pageObjects/components/bottom-panel/cli.ts
  tests/e2e/tests/critical-path/pub-sub/subscribe-unsubscribe.e2e.ts
Labels: feature

#2185 Be/feature ri 4592 triggered functions
  redisinsight/api/src/__mocks__/index.ts
  redisinsight/api/src/__mocks__/triggered-functions.ts
  redisinsight/api/src/app.module.ts
  redisinsight/api/src/app.routes.ts
  redisinsight/api/src/modules/triggered-functions/dto/index.ts
  redisinsight/api/src/modules/triggered-functions/dto/library.dto.ts
  redisinsight/api/src/modules/triggered-functions/models/function.ts
  redisinsight/api/src/modules/triggered-functions/models/index.ts
  redisinsight/api/src/modules/triggered-functions/models/library.ts
  redisinsight/api/src/modules/triggered-functions/models/short-function.ts
  redisinsight/api/src/modules/triggered-functions/models/short-library.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.controller.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.module.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
  redisinsight/api/src/modules/triggered-functions/utils/index.ts
  redisinsight/api/src/modules/triggered-functions/utils/triggered-functions.util.spec.ts
  redisinsight/api/src/modules/triggered-functions/utils/triggered-functions.util.ts
Labels: feature

#2192 update isRedisstack
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/utils/redistack.ts
  redisinsight/ui/src/utils/tests/redistack.spec.ts
Labels: feature

#2193 #RI-4516 - add redis server version in database entity
  redisinsight/api/migration/1686719451753-database-redis-server.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/__mocks__/databases.ts
  redisinsight/api/src/modules/database/database-connection.service.spec.ts
  redisinsight/api/src/modules/database/database-connection.service.ts
  redisinsight/api/src/modules/database/entities/database.entity.ts
  redisinsight/api/src/modules/database/models/database.ts
  redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts
  redisinsight/api/src/modules/database/providers/database-info.provider.ts
  redisinsight/api/src/modules/database/providers/database.factory.ts
  redisinsight/api/src/modules/database/repositories/local.database.repository.spec.ts
  redisinsight/api/src/modules/database/repositories/local.database.repository.ts
  redisinsight/api/test/api/database/GET-databases.test.ts
  redisinsight/api/test/api/database/PATCH-databases-id.test.ts
  redisinsight/api/test/api/database/PUT-databases-id.test.ts
  redisinsight/api/test/api/database/constants.ts
  redisinsight/api/test/helpers/local-db.ts
  redisinsight/ui/src/constants/index.ts
  redisinsight/ui/src/constants/serverVersions.ts
Labels: feature

#2196 #RI-4516 - replace 7.2 version with 7.1
  redisinsight/ui/src/utils/redistack.ts
  redisinsight/ui/src/utils/tests/redistack.spec.ts
Labels: 2.28

#2194 Feature/ri 4516 redisstack conditions
  redisinsight/api/migration/1686719451753-database-redis-server.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/__mocks__/databases.ts
  redisinsight/api/src/modules/database/database-connection.service.spec.ts
  redisinsight/api/src/modules/database/database-connection.service.ts
  redisinsight/api/src/modules/database/entities/database.entity.ts
  redisinsight/api/src/modules/database/models/database.ts
  redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts
  redisinsight/api/src/modules/database/providers/database-info.provider.ts
  redisinsight/api/src/modules/database/providers/database.factory.ts
  redisinsight/api/src/modules/database/repositories/local.database.repository.spec.ts
  redisinsight/api/src/modules/database/repositories/local.database.repository.ts
  redisinsight/api/test/api/database/GET-databases.test.ts
  redisinsight/api/test/api/database/PATCH-databases-id.test.ts
  redisinsight/api/test/api/database/PUT-databases-id.test.ts
  redisinsight/api/test/api/database/constants.ts
  redisinsight/api/test/helpers/local-db.ts
  redisinsight/ui/src/constants/index.ts
  redisinsight/ui/src/constants/serverVersions.ts
  redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/utils/redistack.ts
  redisinsight/ui/src/utils/tests/redistack.spec.ts
Labels: feature

#2206 #RI-4646 - add upload and replace library endpoints
  redisinsight/api/src/modules/triggered-functions/dto/index.ts
  redisinsight/api/src/modules/triggered-functions/dto/upload-library.dto.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.controller.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
Labels: feature

#2208 #RI-4646 - replace config with configuration
  redisinsight/api/src/modules/triggered-functions/dto/upload-library.dto.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
Labels: feature

#2200 #RI-4542 - add font Inconsolata in json view
  redisinsight/ui/src/components/json-viewer/JSONViewer.tsx
  redisinsight/ui/src/packages/clients-list/src/components/json-view/JSONView.tsx
  redisinsight/ui/src/styles/components/_json_view.scss
Labels: 2.28

#2220 #RI-4505 - Update Electron and nodeJS versions
  .circleci/config.yml
  Dockerfile
  api.Dockerfile
  configs/webpack.config.renderer.prod.ts
  configs/webpack.config.renderer.stage.ts
  electron-builder.json
  package.json
  redisinsight/api/package.json
  redisinsight/api/src/modules/ssh/ssh-tunnel.provider.ts
  redisinsight/api/test/test-runs/cloud-st/docker-compose.yml
  redisinsight/api/test/test-runs/local.build.yml
  redisinsight/api/test/test-runs/test.Dockerfile
  redisinsight/api/yarn.lock
  redisinsight/package.json
  redisinsight/yarn.lock
  tests/e2e/helpers/api/api-database.ts
  tests/e2e/package.json
  tests/e2e/pageObjects/browser-page.ts
  tests/e2e/pageObjects/components/browser/bulk-actions.ts
  tests/e2e/tests/critical-path/browser/bulk-delete.e2e.ts
  tests/e2e/tests/critical-path/browser/bulk-upload.e2e.ts
  tests/e2e/tests/critical-path/browser/search-capabilities.e2e.ts
  tests/e2e/tests/critical-path/cli/cli-command-helper.e2e.ts
  tests/e2e/tests/critical-path/database/connecting-to-the-db.e2e.ts
  tests/e2e/tests/critical-path/database/import-databases.e2e.ts
  tests/e2e/tests/critical-path/monitor/save-commands.e2e.ts
  tests/e2e/tests/regression/browser/survey-link.e2e.ts
  tests/e2e/tests/regression/cli/cli-command-helper.e2e.ts
  tests/e2e/tests/regression/database/github.e2e.ts
  tests/e2e/tests/regression/shortcuts/shortcuts.e2e.ts
  tests/e2e/tests/regression/workbench/workbench-pipeline.e2e.ts
  tests/e2e/tests/smoke/cli/cli.e2e.ts
  tests/e2e/tests/smoke/database/add-db-from-welcome-page.e2e.ts
  tests/e2e/tsconfig.testcafe.json
  tests/e2e/web.runner.ts
  tests/e2e/yarn.lock
  yarn.lock
Labels: 2.28

#2221 #RI-4661 - remove duplicates
  redisinsight/api/migration/1687435940110-database-recommendation-unique.ts
  redisinsight/api/migration/index.ts
  redisinsight/api/src/__mocks__/database-recommendation.ts
  redisinsight/api/src/modules/database-recommendation/entities/database-recommendation.entity.ts
  redisinsight/api/src/modules/database-recommendation/models/database-recommendation.ts
  redisinsight/api/src/modules/database-recommendation/repositories/local.database.recommendation.repository.spec.ts
  redisinsight/api/src/modules/database-recommendation/repositories/local.database.recommendation.repository.ts
  redisinsight/api/test/helpers/constants.ts
Labels: bug, 2.28

#2229 #RI- - update redisgears names
  redisinsight/ui/src/slices/interfaces/instances.ts
  redisinsight/ui/src/utils/redistack.ts
  redisinsight/ui/src/utils/tests/redistack.spec.ts
Labels: 2.28

#2232 #RI-4667 - fix sent event
  redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.spec.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
Labels: 2.28

#2231 Feature/ri 4667 telemetry improvements
  redisinsight/api/package.json
  redisinsight/api/src/constants/telemetry-events.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.spec.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.module.ts
  redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.tsx
  redisinsight/ui/src/components/recommendation-voting/styles.module.scss
  redisinsight/ui/src/telemetry/events.ts
  redisinsight/ui/src/utils/recommendation/utils.tsx
  redisinsight/ui/src/utils/tests/recommendation/utils.spec.tsx
Labels: 2.28

#2248 #RI-4583 - add delete library endpoint
  redisinsight/api/src/modules/triggered-functions/dto/delete-library.dto.ts
  redisinsight/api/src/modules/triggered-functions/dto/index.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.controller.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
Labels: 2.30

#2249 #RI-4583 - add delete library
  redisinsight/ui/src/components/notifications/success-messages.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/mocks/handlers/triggeredFunctions/triggeredFunctionsHandler.ts
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/DeleteLibrary.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/DeleteLibrary.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/index.ts
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibraryDetails/LibraryDetails.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibraryDetails/styles.module.scss
  redisinsight/ui/src/slices/interfaces/triggeredFunctions.ts
  redisinsight/ui/src/slices/tests/triggeredFunctions/triggeredFunctions.spec.ts
  redisinsight/ui/src/slices/triggeredFunctions/triggeredFunctions.ts
  redisinsight/ui/src/telemetry/events.ts
Labels: 2.30

#2241 #RI-4672 - fix euiScreenReaderOnly styles
  redisinsight/ui/src/App.scss
Labels: bug, 2.28

#2245 #RI-4674 - fix recommendations list in INSIGHTS_PANEL_CLOSED telemetr…
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
Labels: bug, 2.28

#2256 Feature/ri 4583 delete library
  redisinsight/api/src/modules/triggered-functions/dto/delete-library.dto.ts
  redisinsight/api/src/modules/triggered-functions/dto/index.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.controller.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
  redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
  redisinsight/ui/src/components/notifications/success-messages.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/mocks/handlers/triggeredFunctions/triggeredFunctionsHandler.ts
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/DeleteLibrary.spec.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/DeleteLibrary.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/index.ts
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/DeleteLibrary/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/styles.module.scss
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibraryDetails/LibraryDetails.tsx
  redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibraryDetails/styles.module.scss
  redisinsight/ui/src/slices/interfaces/triggeredFunctions.ts
  redisinsight/ui/src/slices/tests/triggeredFunctions/triggeredFunctions.spec.ts
  redisinsight/ui/src/slices/triggeredFunctions/triggeredFunctions.ts
  redisinsight/ui/src/telemetry/events.ts
Labels: feature, 2.30
