Repository redis/RedisInsight, pull requests merged in 2023-03, with the labels that each got.

#1799 #RI-4244 - update query card styles
  redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
  redisinsight/ui/src/components/query-card/QueryCardHeader/styles.module.scss
  redisinsight/ui/src/components/query-card/styles.module.scss
  redisinsight/ui/src/pages/workbench/constants.ts
Labels: bug

#1769 #RI-4214, #RI-4201, #RI-4200
  configs/webpack.config.web.prod.babel.js
  redisinsight/ui/index.html.ejs
  redisinsight/ui/src/components/monaco-json/MonacoJson.tsx
  redisinsight/ui/src/components/multi-search/MultiSearch.tsx
  redisinsight/ui/src/components/multi-search/styles.module.scss
  redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndex.tsx
  redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.spec.tsx
  redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.tsx
  redisinsight/ui/src/pages/browser/components/create-redisearch-index/styles.module.scss
  redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.spec.tsx
  redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.tsx
  redisinsight/ui/src/styles/components/_popover.scss
Labels: 2.22

#1778 #RI-4124 - add dbindex to telemetry
  redisinsight/api/src/modules/database/database.analytics.spec.ts
  redisinsight/api/src/modules/database/database.analytics.ts
Labels: bug, 2.22

#1830 #RI-4259 - add custom recommendations sorting
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.spec.tsx
  redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/utils.tsx
Labels: feature

#1845 #RI-4075 - add insight panel
  redisinsight/ui/src/assets/img/icons/analysis.svg
  redisinsight/ui/src/assets/img/icons/live-time-recommendations.svg
  redisinsight/ui/src/assets/img/icons/recommendation.svg
  redisinsight/ui/src/assets/img/icons/welcome.svg
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.spec.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/index.ts
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.spec.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/index.ts
  redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/styles.module.scss
  redisinsight/ui/src/components/live-time-recommendations/index.ts
  redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
  redisinsight/ui/src/components/main-router/MainRouter.tsx
  redisinsight/ui/src/constants/api.ts
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/constants/storage.ts
  redisinsight/ui/src/mocks/handlers/index.ts
  redisinsight/ui/src/mocks/handlers/recommendations/index.ts
  redisinsight/ui/src/mocks/handlers/recommendations/recommendationsHandler.ts
  redisinsight/ui/src/mocks/handlers/recommendations/recommendationsReadHandler.ts
  redisinsight/ui/src/pages/instance/InstancePage.spec.tsx
  redisinsight/ui/src/pages/instance/InstancePage.tsx
  redisinsight/ui/src/slices/interfaces/recommendations.ts
  redisinsight/ui/src/slices/recommendations/recommendations.ts
  redisinsight/ui/src/slices/store.ts
  redisinsight/ui/src/slices/tests/recommendations/recommendations.spec.ts
  redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss
  redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss
  redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss
  redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
  redisinsight/ui/src/telemetry/events.ts
  redisinsight/ui/src/utils/test-utils.tsx
Labels: feature

#1864 #RI-4076-4077-4078-4079 - add bigSet, redisVersion, searchJSON and RT…
  redisinsight/api/src/constants/recommendations.ts
  redisinsight/api/src/constants/redis-modules.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
  redisinsight/api/src/modules/browser/services/z-set-business/z-set-business.service.spec.ts
  redisinsight/api/src/modules/browser/services/z-set-business/z-set-business.service.ts
  redisinsight/api/src/modules/database-recommendation/models/database-recommendation.ts
  redisinsight/api/src/modules/database-recommendation/models/index.ts
  redisinsight/api/src/modules/database-recommendation/models/searchJSON.ts
  redisinsight/api/src/modules/database-recommendation/models/searchString.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
  redisinsight/api/src/modules/database-recommendation/scanner/recommendations.scanner.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-set.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redi-search.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-JSON.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-JSON.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-string.strategy.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/index.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/timestamp.spec.ts
  redisinsight/api/src/modules/database-recommendation/scanner/utils/timestamp.ts
  redisinsight/api/src/modules/database/database-connection.service.spec.ts
  redisinsight/api/src/modules/database/database-connection.service.ts
  redisinsight/api/src/modules/recommendation/recommendation.service.ts
  redisinsight/api/src/utils/index.ts
  redisinsight/api/src/utils/recommendation-helper.spec.ts
  redisinsight/api/src/utils/recommendation-helper.ts
Labels: 2.24

#1868 #RI-4076-4077-4078-4079 - update styles and hihglighting
  redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
  redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
  redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
  redisinsight/ui/src/constants/dbAnalysisRecommendations.json
  redisinsight/ui/src/pages/instance/InstancePage.tsx
  redisinsight/ui/src/slices/recommendations/recommendations.ts
Labels: feature
